grafana:
  enabled: true

  adminUser: admin
  adminPassword: admin123

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - grafana.10.10.10.201.nip.io
    path: /
    pathType: Prefix

prometheus:
  enabled: true

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - prometheus.10.10.10.201.nip.io
    paths:
      - /
    pathType: Prefix

  prometheusSpec:
    retention: 7d
    scrapeInterval: 30s
    evaluationInterval: 30s

alertmanager:
  enabled: true

  service:
    type: ClusterIP

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  enabled: true
