{{- if .Values.configMapHtml.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }

      location /stub_status {
        stub_status;
        access_log off;
        allow 127.0.0.1;
        deny all;
      }
    }
{{- end }}