{{- if .Values.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodePort.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.labels.app }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app.labels.app }}
  ports:
    - name: http
      port: {{ .Values.nodePort.port }}
      targetPort: {{ .Values.nodePort.targetPort }}
      nodePort: {{ .Values.nodePort.nodePort }}
{{- end }}
