apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.labels.app }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app.labels.app }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
